#Run locally: CI_REGISTRY=gitlab.lrz.de:5005 CI_PROJECT_NAMESPACE=proteomics/container CI_PROJECT_NAME=enrichment-server CI_COMMIT_REF_SLUG=latest  docker compose up

version: '3.6'

services:
  enrichment_server:
    restart: unless-stopped
    environment:
      - CI_REGISTRY
      - CI_PROJECT_NAMESPACE
      - CI_PROJECT_NAME
      - CI_COMMIT_REF_SLUG
      - CI_DEPLOY_TAG
      - CI_DEPLOY_NETWORK
      - CI_PUBLISH
      - PRODUCTION=1
      - PORT=4321
    build: . #TODO: CI prints 'Ignoring unsupported options: build', not sure if I need this
    image: "${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}"
    networks:
      - INTERNAL
      - EXTERNAL
    ports:
      - "4321:4321"
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 5
        window: 10s
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      labels:
        - "traefik.port=4321"
        - "traefik.backend=${CI_COMMIT_REF_SLUG}_${CI_PROJECT_NAME}"
        - "traefik.frontend.rule=PathPrefixStrip:/${CI_COMMIT_REF_SLUG}_${CI_PROJECT_NAME}/"
        - "traefik.backend.loadbalancer.sticky=true"
        - "traefik.tags=${CI_COMMIT_REF_SLUG},${CI_DEPLOY_TAG},${CI_PUBLISH}"
        - "traefik.docker.network=EXTERNAL"
      resources:
        limits:
          memory: 8192M
        reservations:
          memory: 5000M
networks:
  EXTERNAL:
    external: true
  INTERNAL:
    external: true