version: '3.6'

services:
  enrichment_server:
    restart: unless-stopped
    environment:
      - CI_REGISTRY
      - CI_PROJECT_NAMESPACE
      - CI_PROJECT_NAME
      - CI_COMMIT_REF_SLUG
      - CI_DEPLOY_TAG
      - CI_DEPLOY_NETWORK
      - CI_PUBLISH
    build: . #TODO: CI prints 'Ignoring unsupported options: build', not sure if I need this
    image: "${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}"
    ports:
      - "4321:4321"
    #TODO: Could be that this only works when using traefik, maybe delete
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          memory: 5000M
        reservations:
          memory: 250M